# Generated by Django 4.2.1 on 2023-05-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instance_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer', models.CharField(blank=True, max_length=999, null=True)),
                ('iterations', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'ENQUEUE'), (1, 'COMPLETED')], default=0)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_items', to='base.instance')),
            ],
        ),
    ]
